<?php include 'partials/hero.php'; ?>
<?php include 'partials/about.php'; ?>
<?php include 'partials/benefit.php'; ?>
<?php include 'partials/failure.php'; ?>
<?php include 'partials/point.php'; ?>
<?php include 'partials/testimonies.php'; ?>
<?php include 'partials/faq.php'; ?>
<?php include 'partials/flow.php'; ?>
<?php include 'partials/contact.php'; ?>